# Generated by Django 5.2.5 on 2025-08-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0002_country_region_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='official_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
