# Generated by Django 5.2.5 on 2025-08-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0002_rating_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='review',
        ),
    ]
