# Generated by Django 5.2.5 on 2025-08-13 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0003_park_official_website'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='park',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ParkIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('source_id', models.CharField(max_length=100)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='parks.park')),
            ],
            options={
                'unique_together': {('source_name', 'source_id')},
            },
        ),
    ]
