# Generated by Django 5.2.5 on 2025-08-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0004_alter_park_unique_together_parkidentifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='flags/'),
        ),
        migrations.AlterField(
            model_name='park',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
